### ISSUE TITLE
登入出現Invalid account

### ISSUE THREAD

**Issue by Eddie0226** [opsun/MT4Wrapper#4]
你好，我在用Test.java測試時，可以正確地連接到我的主機
不過在呼叫login時出現錯誤代碼65
檢查該代碼是Invalid account

不過我有確認過這組帳號密碼是可以登入PPDExchange4
不曉得我哪邊出了問題
兩個dll檔案(mtmanapi.dll和MT4Warpper.dll)我也有丟到C:\Windows\SysWOW64底下
我的作業系統是Win10 64bit

希望你可以幫忙看一下可能錯誤的方向
謝謝~

**Comment by opsun** [comment]
PPDExchange4 没用过，也许你登陆的并不是MT4Manager。

**Comment by Eddie0226** [comment]
應該都是MetaTrader，我對程式交易這方面還是新手
想請問還有甚麼方式可以驗證登入程式的功能嗎?

![image](https://cloud.githubusercontent.com/assets/29175148/26791225/f7cd5cb2-4a48-11e7-8d0b-8395d1e21fd9.png)

**Comment by Eddie0226** [comment]
解決了
原來是我用的帳號非Manager，是一般Client權限
謝謝你之前幫忙回覆
